# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew clean testClasses
  branches:
    master:
      - step:
          name: Deploy to test
          deployment: test
          script:
            - bash ./gradlew clean testClasses
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_TEST.git HEAD:master